// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0y7NHlY_CVPq-nywWVRwtRPSARAfrgGE',
    appId: '1:922881399744:web:3ba9da4637fb343fba0625',
    messagingSenderId: '922881399744',
    projectId: 'reemo-nl-task',
    authDomain: 'reemo-nl-task.firebaseapp.com',
    storageBucket: 'reemo-nl-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiSygW10MB1AQbFTwZyR9-kjl8vzLEMGI',
    appId: '1:922881399744:android:ee633afb3814d092ba0625',
    messagingSenderId: '922881399744',
    projectId: 'reemo-nl-task',
    storageBucket: 'reemo-nl-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUYWHg7MTwDm0uWwF31pzY4DRgvILSwPQ',
    appId: '1:922881399744:ios:4c5c58ac620423e0ba0625',
    messagingSenderId: '922881399744',
    projectId: 'reemo-nl-task',
    storageBucket: 'reemo-nl-task.appspot.com',
    iosBundleId: 'com.app.reemoNlTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUYWHg7MTwDm0uWwF31pzY4DRgvILSwPQ',
    appId: '1:922881399744:ios:4c5c58ac620423e0ba0625',
    messagingSenderId: '922881399744',
    projectId: 'reemo-nl-task',
    storageBucket: 'reemo-nl-task.appspot.com',
    iosBundleId: 'com.app.reemoNlTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0y7NHlY_CVPq-nywWVRwtRPSARAfrgGE',
    appId: '1:922881399744:web:e2c5f7329e264060ba0625',
    messagingSenderId: '922881399744',
    projectId: 'reemo-nl-task',
    authDomain: 'reemo-nl-task.firebaseapp.com',
    storageBucket: 'reemo-nl-task.appspot.com',
  );
}
